name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  metis_api_key:
    description: metis api key project identifier
    required: true
    default: ''
  target_url:
    description: target url
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
